### ISSUE TITLE
Duplicate item list Qbox & Ox inventory

### ISSUE THREAD

**Issue by LordChunk** [Qbox-project/txAdminRecipe#68]
### Summary

Scaffolded servers generate two separate item lists in qbox & ox inventory

### Reproduction

1. Scaffold a server
2. Create a character
3. Standard inventory items like ID cards show no images
This is caused by different item names used in qbox and ox inventory (qbox uses ``id_card`` and ox_inventory ``card_id``).

### Expected behavior

Scaffolded servers should be configured to use either the qbox or ox inventory item list.

### Actual behavior

Plugins use either itemlist depending on their default configuration.

### Current Version

qbox v1.12.0 & ox inventory v2.40.1

### Custom Resources

None

**Comment by LordChunk** [comment]
Referencing this PR as it would resolve this issue: https://github.com/Qbox-project/qbx_core/pull/451

**Comment by Manason** [comment]
The weapons and items in qbx_core are now empty lists.
